## Introduction to NumPy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
# 1d array
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [8]:
# 2d array
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
new_array=np.array([1,2,3])


In [11]:
new_array_1=np.array([[10,11,12],[13,14,15]])
new_array_1

array([[10, 11, 12],
       [13, 14, 15]])

In [15]:
# zeros{array}
zero=np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
# ones{array}
one=np.ones(5)
one

array([1., 1., 1., 1., 1.])

In [18]:
zeros_2=np.zeros([2,3])
zeros_2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
one_2=np.ones([5,10])
one_2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
# random integers
random_integers=np.random.rand(2,4)
random_integers

array([[0.51226239, 0.05513575, 0.49669918, 0.87171786],
       [0.18701909, 0.03297736, 0.32003942, 0.17735597]])

In [25]:
random_integers=np.random.rand(6,7)
random_integers

array([[0.346721  , 0.54172614, 0.56478169, 0.8117444 , 0.48859774,
        0.11731966, 0.65024615],
       [0.82061739, 0.09323741, 0.00427312, 0.42562983, 0.10756788,
        0.13517781, 0.29548826],
       [0.49203536, 0.0980408 , 0.27142197, 0.79812713, 0.57098147,
        0.30110598, 0.65128764],
       [0.99218403, 0.15083985, 0.11413922, 0.54831125, 0.16410275,
        0.24687756, 0.25978519],
       [0.08387589, 0.65316853, 0.82732597, 0.40569777, 0.53899439,
        0.97436945, 0.95675493],
       [0.43143916, 0.45889972, 0.02429167, 0.41628863, 0.71354691,
        0.34336958, 0.09914207]])

## Basic array attributes:
# -shape
# -dtype
# -size
# -ndim


In [27]:
arr=np.array([[10,20,30],[40,50,60]])
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [28]:
arr.shape

(2, 3)

In [29]:
arr.dtype

dtype('int64')

In [30]:
arr.size

6

In [31]:
arr.ndim

2