In [ ]:
import numpy as np

#array using zeros
arr=np.zeros(3)
arr

array([0., 0., 0.])

In [ ]:
#array using all ones
arr=np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#using arange
arr=np.arange(0,21,2) #(start,stop,step)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
#using linspace
linespace=np.linspace(0,1,5)
linespace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
#ussing random.rand()
random_array=np.random.rand(2,3)
random_array

array([[0.1128679 , 0.56726651, 0.31381203],
       [0.40449536, 0.11786391, 0.80042494]])

In [7]:
#random.randn()
random_array=np.random.randn(2,3)
random_array

array([[-0.28422089,  0.42768721,  0.23294434],
       [-0.04457624,  1.13202049,  1.05011728]])

In [9]:
#random.randint()
random_array=np.random.randint(1,100,size=(5,5)) #(low,high,size)
random_array

array([[14, 50, 76, 12, 57],
       [58, 73, 86, 10, 10],
       [64, 92, 49, 11, 32],
       [62, 59, 12, 83, 27],
       [23, 12, 71,  4, 15]])

In [40]:
#identity matrix
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
random_array=np.random.randint(100,400,size=(10,10)) #(low,high,size)
random_array

array([[251, 307, 146, 230, 169, 352, 199, 376, 228, 134],
       [391, 339, 351, 205, 389, 148, 376, 305, 310, 246],
       [134, 291, 325, 272, 211, 177, 124, 127, 107, 146],
       [352, 160, 249, 144, 210, 152, 326, 265, 263, 341],
       [314, 318, 305, 252, 298, 106, 159, 257, 235, 302],
       [333, 192, 263, 131, 106, 397, 249, 276, 178, 295],
       [321, 236, 190, 119, 393, 253, 121, 278, 100, 267],
       [278, 104, 107, 232, 301, 165, 148, 241, 180, 362],
       [332, 101, 325, 276, 330, 379, 194, 312, 304, 319],
       [169, 320, 162, 292, 162, 214, 273, 352, 293, 130]])

In [ ]:
#slicing in arrays

arr=np.array([10,20,30,40,50,60,70])


In [13]:
arr[2:5]

array([30, 40, 50])

In [15]:
arr[:4]

array([10, 20, 30, 40])

In [16]:
arr[1:]

array([20, 30, 40, 50, 60, 70])

In [17]:
# reverse the array
arr[::-1]

array([70, 60, 50, 40, 30, 20, 10])

In [ ]:
arr[::2] 

array([10, 30, 50, 70])

In [19]:
#negative indexing
arr[-1]

np.int64(70)

In [20]:
#last 3 elements
arr[-3::]

array([50, 60, 70])

In [21]:
# slicing in 2d arrays
matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [12,13,14,15]])
                  


In [22]:
#Row slicing
#first two rows
matrix[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
#column slicing
matrix[:,1]

array([ 2,  6, 10, 13])

In [25]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [12, 13, 14, 15]])

In [26]:
matrix[1:3,1:4]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [27]:
matrix[0:2,1:4]

array([[2, 3, 4],
       [6, 7, 8]])

In [30]:
matrix[2:4,0:3]

array([[ 9, 10, 11],
       [12, 13, 14]])

In [32]:
matrix[3,2]

np.int64(14)

In [33]:
#slice creates a VIEW 
view_arr=arr[1:4]
view_arr

array([20, 30, 40])

In [ ]:
#change the element of array
view_arr[0]=99
view_arr

array([99, 30, 40])

In [35]:
arr

array([10, 99, 30, 40, 50, 60, 70])

In [36]:
#copy array
copy_arr=arr.copy()
copy_arr

array([10, 99, 30, 40, 50, 60, 70])